theme: jekyll-theme-minimal

title: Prakhar Mishra

name: Prakhar Mishra

description: NLP | AI | Developer | Python

avatar: https://yt3.ggpht.com/-KXG_2aoDTps/AAAAAAAAAAI/AAAAAAAAAAA/Xq-uu8uusK0/s900-c-k-no-mo-rj-c0xffffff/photo.jpg
